import {mkdir,copyFile,readFile,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildInjection} from '../extension/payload.mjs';
const root=dirname(dirname(fileURLToPath(import.meta.url))),out=join(root,'.build/site');
await mkdir(join(out,'animation/assets'),{recursive:true});await mkdir(join(out,'background'),{recursive:true});
for(const name of ['index.html','site.css','favicon.svg'])await copyFile(join(root,'web',name),join(out,name));
for(const name of ['style.css','image-settings.js','animation.js'])await copyFile(join(root,name),join(out,'animation',name));
for(const name of ['theme.js','contours.js','avatar.jpg','artwork.jpg','avatar-motion.gif'])await copyFile(join(root,'assets',name),join(out,'animation/assets',name));
let animation=await readFile(join(root,'index.html'),'utf8');
animation=animation.replace('<header class="preview-heading">','<header class="preview-heading"><a href="../" style="color:inherit;text-decoration:none">← 首页</a>');
await writeFile(join(out,'animation/index.html'),animation);
let background=await readFile(join(root,'extension/preview.html'),'utf8');
background=background.replace('外部扩展验证页','背景体验 · Codex 背景渲染').replace('<b>外部扩展验证</b>','<b>Codex 背景渲染</b>').replace('这是本地测试页，','这是背景预览页面，').replace('LOCAL PREVIEW / 原应用包不变','BROWSER PREVIEW / 自选图片仅保存在浏览器').replace('⌘⌥B','Ctrl+Alt+B').replace('测试设置入口','换图与设置').replace('测试恢复外观','恢复外观').replace('<div class="test-controls">','<div class="test-controls"><a href="../" style="padding:10px;color:inherit;text-decoration:none">← 首页</a>');
await writeFile(join(out,'background/index.html'),background);
await writeFile(join(out,'background/extension.js'),await buildInjection(root));
await writeFile(join(out,'background/controls.js'),`document.querySelector('#restore').addEventListener('click',()=>window.__aemeathExtension?.dispose());document.querySelector('#settings').addEventListener('click',()=>window.__aemeathExtension?.openSettings());document.querySelector('#ready').addEventListener('click',event=>event.target.textContent='点击成功');`);
await writeFile(join(out,'.nojekyll'),'');
console.log(out);
